version: '2'

services:
    ksam-loopa:
        image: edithzavala/ksam
        ports:
            - "8090:8080"
        volumes:
        - ~/ksam_data/:/tmp/weka
        - ./config:/tmp/config
        network_mode: host
        command: "application.json --server.port=8090"
