version: '2'

services:
    ksam-loopa:
        image: edithzavala/ksam:latest
        ports:
            - "8090:8080"
        volumes:
        - /home/revere/ezb/ksam_data/:/tmp/weka
        network_mode: host
        command: "/application.json --server.port=8090"
